define([], function() {
  return {
    "PropertyPaneDescription": "Design template for how to create a help desk ticket entry system.",
    "GroupName": "Configuration",
    "TitleFieldLabel": "Card Title",
    "IconPropertyFieldLabel": "Card Icon",
    "CardViewText": "Create a new request",
    "NewFormHeader": "Create a request",
    "ConfirmFormHeader": "Please confirm your data",
    "IncidentNumberLabel": "Request number",
    "RequestedByLabel": "Raised by",
    "CreatedDateLabel": "Opened",
    "CategoryLabel": "Category",
    "CategoryPlaceholder": "Choose a category",
    "UrgencyLabel": "Urgency",
    "UrgencyPlaceholder": "Choose an option",
    "StateLabel": "State",
    "StatePlaceholder": "Choose an option",
    "DescriptionLabel": "Short description (Max 300 characters)",
    "DescriptionPlaceholder": "Please enter a short description",
    "LocationLabel": "Tell us your location",
    "AddLocationLabel": "Add a location",
    "UploadImageLabel": "Upload Image",
    "AddImageLabel": "Add an image",
    "CancelButtonLabel": "Discard",
    "SubmitButtonLabel": "Submit",
    "ConfirmButtonLabel": "Confirm",
    "ImageUrl": "https://vivaconnectionssql9eb8.blob.core.windows.net/img/myhelpimage-1.svg",
    "ProfileImageUrl": "https://secure.gravatar.com/avatar/ef9c26e764df8eeed6304f719f580706?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAG-4.png",
  }
});